import React, { useState } from 'react';
import { Helmet } from 'react-helmet';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { Copy, RefreshCw, Shield, Loader2, KeyRound, Lock, AlertTriangle } from 'lucide-react';
import { useToast } from '@/components/ui/use-toast';

import { useAuth } from '@/contexts/SupabaseAuthContext';
import { AppLoginModal } from '@/components/apps/shared/AppLoginModal';
import { AboutSection, ManualSection, FAQSection, CommunitySection } from '@/components/apps/shared/AppSections';
import { AppTabsLayout } from '@/components/apps/shared/AppTabsLayout';

const passwordData = {
  about: {
    title: "Password Generator",
    description: "Create highly secure, random passwords instantly to protect your accounts from being compromised.",
    features: [
      { icon: <Shield className="w-6 h-6" />, title: "Secure Generation", desc: "Uses cryptographically secure methods for randomness." },
      { icon: <KeyRound className="w-6 h-6" />, title: "Customizable", desc: "Choose length and character types to meet any requirement." },
      { icon: <Lock className="w-6 h-6" />, title: "No Tracking", desc: "Passwords are generated locally in your browser." },
    ],
    benefits: [
      "Prevent account hacking with complex passwords.",
      "Meet strict corporate or website password requirements easily.",
      "Ensure uniqueness across all your digital identities.",
      "Completely private – we never see or store your passwords."
    ]
  },
  manual: {
    title: "Password Generator",
    steps: [
      { title: "Set Length", desc: "Use the slider to choose a password length (16+ recommended)." },
      { title: "Select Characters", desc: "Check the boxes for uppercase, lowercase, numbers, and symbols." },
      { title: "Generate", desc: "Click the Generate Password button to create a new one." },
      { title: "Copy & Use", desc: "Click the copy icon and paste it into your password manager or site." }
    ],
    tips: [
      "Never reuse the same password across multiple sites.",
      "Use a password manager to store these complex passwords.",
      "Longer passwords are exponentially harder to crack."
    ]
  },
  faq: [
    { q: "Is this password generator safe?", a: "Yes, it generates passwords entirely in your browser using secure random number generation. Nothing is sent to our servers." },
    { q: "How long should my password be?", a: "Security experts recommend at least 16 characters for maximum security." },
    { q: "Do you save my generated passwords?", a: "No, we do not save, track, or transmit any passwords generated by this tool." }
  ]
};

const PasswordGeneratorPage = () => {
  const { isAuthenticated, loading: authLoading } = useAuth();
  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);
  const [authView, setAuthView] = useState('login');

  const { toast } = useToast();
  const [password, setPassword] = useState('');
  const [length, setLength] = useState(16);
  const [includeUppercase, setIncludeUppercase] = useState(true);
  const [includeLowercase, setIncludeLowercase] = useState(true);
  const [includeNumbers, setIncludeNumbers] = useState(true);
  const [includeSymbols, setIncludeSymbols] = useState(true);

  const generatePassword = () => {
    let charset = '';
    if (includeUppercase) charset += 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
    if (includeLowercase) charset += 'abcdefghijklmnopqrstuvwxyz';
    if (includeNumbers) charset += '0123456789';
    if (includeSymbols) charset += '!@#$%^&*()_+-=[]{}|;:,.<>?';

    if (charset === '') {
      toast({ 
        title: 'No character types selected', 
        description: 'Please select at least one character type.', 
        variant: 'destructive' 
      });
      return;
    }

    let newPassword = '';
    for (let i = 0; i < length; i++) {
      newPassword += charset.charAt(Math.floor(Math.random() * charset.length));
    }
    setPassword(newPassword);
  };

  const copyToClipboard = async () => {
    if (!password) {
      toast({ title: 'No password to copy', variant: 'destructive' });
      return;
    }
    try {
      await navigator.clipboard.writeText(password);
      toast({ title: 'Password copied!', description: 'Password has been copied to clipboard.' });
    } catch (err) {
      toast({ title: 'Failed to copy', variant: 'destructive' });
    }
  };

  const tabsConfig = [
    { id: 'about', label: 'About', content: <AboutSection {...passwordData.about} /> },
    { id: 'manual', label: 'Manual', content: <ManualSection {...passwordData.manual} /> },
    { id: 'faq', label: 'FAQ', content: <FAQSection faqs={passwordData.faq} /> },
    { id: 'community', label: 'Community', content: <CommunitySection appId="password-generator" /> }
  ];

  return (
    <>
      <Helmet>
        <title>Password Generator - A2Z Utility Hub</title>
        <meta name="description" content="Generate strong, secure passwords with customizable options. Create random passwords instantly." />
      </Helmet>
      <div className="full-width-container py-12">
        <div className="text-center mb-12">
          <div className="flex justify-center mb-4">
            <div className="p-3 bg-brand-primary/10 rounded-2xl">
              <Shield className="w-10 h-10 text-brand-primary" />
            </div>
          </div>
          <h1 className="text-4xl font-extrabold tracking-tight">Secure Password Generator</h1>
          <p className="mt-2 text-lg text-muted-foreground">Create strong, random passwords to protect your accounts.</p>
        </div>

        {authLoading ? (
          <div className="flex min-h-[60vh] items-center justify-center">
            <Loader2 className="w-10 h-10 animate-spin text-primary" />
          </div>
        ) : !isAuthenticated ? (
          <div className="min-h-[40vh] flex items-center justify-center p-4">
            <Card className="w-full max-w-md shadow-xl border-primary/10 bg-card text-center">
              <CardHeader className="pb-6 pt-8">
                <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mx-auto mb-6 ring-8 ring-primary/5">
                  <Shield className="w-10 h-10 text-primary" />
                </div>
                <CardTitle className="text-3xl font-extrabold tracking-tight">Password Generator</CardTitle>
                <CardDescription className="text-base mt-3 text-muted-foreground">
                  Please log in to access the Password Generator tool.
                </CardDescription>
              </CardHeader>
              <CardContent className="flex flex-col gap-4 pb-8 px-8">
                <Button size="lg" className="w-full text-md font-semibold h-12" onClick={() => { setAuthView('login'); setIsAuthModalOpen(true); }}>
                  Login to Continue
                </Button>
                <Button variant="outline" size="lg" className="w-full h-12 border-primary/20 hover:bg-primary/5" onClick={() => { setAuthView('signup'); setIsAuthModalOpen(true); }}>
                  Create an Account
                </Button>
              </CardContent>
            </Card>
          </div>
        ) : (
          <div className="max-w-2xl mx-auto">
            <Card className="shadow-lg">
              <CardHeader>
                <CardTitle>Generated Password</CardTitle>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="flex gap-2">
                  <Input 
                    value={password} 
                    readOnly 
                    placeholder="Your password will appear here..."
                    className="font-mono text-lg"
                  />
                  <Button onClick={copyToClipboard} variant="outline" size="icon">
                    <Copy className="h-4 w-4" />
                  </Button>
                </div>

                <div className="space-y-4">
                  <div className="space-y-2">
                    <Label>Password Length: {length}</Label>
                    <Slider
                      value={[length]}
                      onValueChange={(val) => setLength(val[0])}
                      min={8}
                      max={64}
                      step={1}
                    />
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="flex items-center space-x-2">
                      <Checkbox 
                        id="uppercase" 
                        checked={includeUppercase}
                        onCheckedChange={setIncludeUppercase}
                      />
                      <Label htmlFor="uppercase" className="cursor-pointer">Uppercase (A-Z)</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Checkbox 
                        id="lowercase" 
                        checked={includeLowercase}
                        onCheckedChange={setIncludeLowercase}
                      />
                      <Label htmlFor="lowercase" className="cursor-pointer">Lowercase (a-z)</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Checkbox 
                        id="numbers" 
                        checked={includeNumbers}
                        onCheckedChange={setIncludeNumbers}
                      />
                      <Label htmlFor="numbers" className="cursor-pointer">Numbers (0-9)</Label>
                    </div>
                    <div className="flex items-center space-x-2">
                      <Checkbox 
                        id="symbols" 
                        checked={includeSymbols}
                        onCheckedChange={setIncludeSymbols}
                      />
                      <Label htmlFor="symbols" className="cursor-pointer">Symbols (!@#$%)</Label>
                    </div>
                  </div>
                </div>

                <Button onClick={generatePassword} className="w-full" size="lg">
                  <RefreshCw className="mr-2 h-4 w-4" /> Generate Password
                </Button>
              </CardContent>
            </Card>
          </div>
        )}

        <AppTabsLayout tabsConfig={tabsConfig} />

      </div>
      <AppLoginModal isOpen={isAuthModalOpen} onClose={() => setIsAuthModalOpen(false)} defaultView={authView} />
    </>
  );
};

export default PasswordGeneratorPage;